const {
  urls,
  validation,
  match,
  registerController,
} = require("../../../utils/controller");

const config = {
  name: urls.residenceCountry,
  previous: [
    {
      page: urls.nationalityOther,
      condition: {
        field: urls.nationality,
        value: "other",
        match: match.value,
      },
    },
    {
      page: urls.nationality,
    },
  ],
  next: [
    {
      page: urls.residenceCountryIneligible,
      condition: {
        field: urls.residenceCountry,
        value: 'abroad',
        match: match.value,
      },
    },
    {
      page: urls.countryOutsideUKDuration,
      condition: {
         field: urls.nationality,
        value: 'british',
        match: match.value,
      },
    },
    {
      page: urls.countryOutsideUKDuration,
      condition: {
         field: urls.nationality,
        value: 'irish',
        match: match.value,
      },
    },
    {
      page: urls.livingInUk,
      condition: {
        field: urls.nationalityOther,
        value: [
          "Austrian",
          "Belgian",
          "Bulgarian",
          "Croatian",
          "Cypriot",
          "Czech",
          "Danish",
          "Dutch",
          "Estonian",
          "Finnish",
          "French",
          "German",
          "Greek",
          "Hungarian",
          "Icelandic",
          "Irish",
          "Italian",
          "Latvian",
          "Liechtenstein citizen",
          "Lithuanian",
          "Luxembourger",
          "Maltese",
          "Norwegian",
          "Polish",
          "Portuguese",
          "Romanian",
          "Slovak",
          "Slovenian",
          "Spanish",
          "Swedish",
          "Swiss",
        ],
        match: match.anyOne,
      },
    },
    {
      page: urls.countryOutsideUKDuration,
      condition: {
        field: urls.nationalityOther,
        value: [
          "Afghan",
          "Albanian",
          "Algerian",
          "American",
          "Andorran",
          "Angolan",
          "Anguillan",
          "Argentine",
          "Armenian",
          "Australian",
          "Azerbaijani",
          "Bahamian",
          "Bahraini",
          "Bangladeshi",
          "Barbadian",
          "Belarusian",
          "Belizean",
          "Beninese",
          "Bermudian",
          "Bhutanese",
          "Bolivian",
          "Botswanan",
          "Brazilian",
          "British",
          "British Virgin Islander",
          "Bruneian",
          "Burkinan",
          "Burmese",
          "Burundian",
          "Cambodian",
          "Cameroonian",
          "Canadian",
          "Cape Verdean",
          "Cayman Islander",
          "Central African",
          "Chadian",
          "Chilean",
          "Chinese",
          "Citizen of Antigua and Barbuda",
          "Citizen of Bosnia and Herzegovina",
          "Citizen of Guinea-Bissau",
          "Citizen of Kiribati",
          "Citizen of Seychelles",
          "Citizen of the Dominican Republic",
          "Citizen of Vanuatu",
          "Colombian",
          "Comoran",
          "Congolese (Congo)",
          "Congolese (DRC)",
          "Cook Islander",
          "Costa Rican",
          "Cuban",
          "Cymraes",
          "Cymro",
          "Djiboutian",
          "Dominican",
          "East Timorese",
          "Ecuadorean",
          "Egyptian",
          "Emirati",
          "English",
          "Equatorial Guinean",
          "Eritrean",
          "Ethiopian",
          "Faroese",
          "Fijian",
          "Filipino",
          "Gabonese",
          "Gambian",
          "Georgian",
          "Ghanaian",
          "Gibraltarian",
          "Greenlandic",
          "Grenadian",
          "Guamanian",
          "Guatemalan",
          "Guinean",
          "Guyanese",
          "Haitian",
          "Honduran",
          "Hong Konger",
          "Indian",
          "Indonesian",
          "Iranian",
          "Iraqi",
          "Israeli",
          "Ivorian",
          "Jamaican",
          "Japanese",
          "Jordanian",
          "Kazakh",
          "Kenyan",
          "Kittitian",
          "Kosovan",
          "Kuwaiti",
          "Kyrgyz",
          "Lao",
          "Lebanese",
          "Liberian",
          "Libyan",
          "Macanese",
          "Macedonian",
          "Malagasy",
          "Malawian",
          "Malaysian",
          "Maldivian",
          "Malian",
          "Marshallese",
          "Martiniquais",
          "Mauritanian",
          "Mauritian",
          "Mexican",
          "Micronesian",
          "Moldovan",
          "Monegasque",
          "Mongolian",
          "Montenegrin",
          "Montserratian",
          "Moroccan",
          "Mosotho",
          "Mozambican",
          "Namibian",
          "Nauruan",
          "Nepalese",
          "New Zealander",
          "Nicaraguan",
          "Nigerian",
          "Nigerien",
          "Niuean",
          "North Korean",
          "Northern Irish",
          "Omani",
          "Pakistani",
          "Palauan",
          "Palestinian",
          "Panamanian",
          "Papua New Guinean",
          "Paraguayan",
          "Peruvian",
          "Pitcairn Islander",
          "Prydeinig",
          "Puerto Rican",
          "Qatari",
          "Russian",
          "Rwandan",
          "Salvadorean",
          "Sammarinese",
          "Samoan",
          "Sao Tomean",
          "Saudi Arabian",
          "Scottish",
          "Senegalese",
          "Serbian",
          "Sierra Leonean",
          "Singaporean",
          "Solomon Islander",
          "Somali",
          "South African",
          "South Korean",
          "South Sudanese",
          "Sri Lankan",
          "St Helenian",
          "St Lucian",
          "Stateless",
          "Sudanese",
          "Surinamese",
          "Swazi",
          "Syrian",
          "Taiwanese",
          "Tajik",
          "Tanzanian",
          "Thai",
          "Togolese",
          "Tongan",
          "Trinidadian",
          "Tristanian",
          "Tunisian",
          "Turkish",
          "Turkmen",
          "Turks and Caicos Islander",
          "Tuvaluan",
          "Ugandan",
          "Ukrainian",
          "Uruguayan",
          "Uzbek",
          "Vatican citizen",
          "Venezuelan",
          "Vietnamese",
          "Vincentian",
          "Wallisian",
          "Welsh",
          "Yemeni",
          "Zambian",
          "Zimbabwean",
        ],
        match: match.anyOne,
      },
    },
  ],
  validation: {
    type: validation.radios,
    errors: {
      required: "Select the country where you live",
    },
  },
};

module.exports = registerController(config.name, config);
