const {
  urls,
  validation,
  match,
  registerController,
} = require("../../../utils/controller");

const config = {
  name: urls.residenceCountry,
  previous: [
    {
      page: urls.nationalityOther,
      condition: {
        field: urls.nationality,
        value: "other",
        match: match.value,
      },
    },
    {
      page: urls.nationality,
    },
  ],
  next: [
    {
      page: urls.livingInUk,
      condition: {
        field: urls.nationalityOther,
        value: [
          "Austrian",
          "Belgian",
          "Bulgarian",
          "Croatian",
          "Cypriot",
          "Czech",
          "Danish",
          "Dutch",
          "Estonian",
          "Finnish",
          "French",
          "German",
          "Greek",
          "Hungarian",
          "Icelandic",
          "Irish",
          "Italian",
          "Latvian",
          "Liechtenstein citizen",
          "Lithuanian",
          "Luxembourger",
          "Maltese",
          "Norwegian",
          "Polish",
          "Portuguese",
          "Romanian",
          "Slovakian",
          "Slovenian",
          "Spanish",
          "Swedish",
          "Swiss",
        ],
        match: match.anyOne,
      },
    },
    {
      page: urls.countryOutsideUKDuration,
      condition: {
        field: urls.nationalityOther,
        value: [
          "Austrian",
          "Belgian",
          "Bulgarian",
          "Croatian",
          "Cypriot",
          "Czech",
          "Danish",
          "Dutch",
          "Estonian",
          "Finnish",
          "French",
          "German",
          "Greek",
          "Hungarian",
          "Icelandic",
          "Irish",
          "Italian",
          "Latvian",
          "Liechtenstein citizen",
          "Lithuanian",
          "Luxembourger",
          "Maltese",
          "Norwegian",
          "Polish",
          "Portuguese",
          "Romanian",
          "Slovakian",
          "Slovenian",
          "Spanish",
          "Swedish",
          "Swiss",
        ],
        match: match.none,
      },
    },
    {
      page: urls.residenceCountryIneligible,
      condition: {
        field: urls.residenceCountry,
        value: 'abroad',
        match: match.value,
      },
    },
  ],

  validation: {
    type: validation.radios,
    errors: {
      required: "Select the country where you live",
    },
  },
};

module.exports = registerController(config.name, config);
