
module.exports = {
  urls: {
    // start
    root: '/',
    start: 'start',
    beforeYouStart: 'before-you-start',
    beforeYouStartIneligible: 'before-you-start-ineligible',
    helpingSomeoneIntro: 'helping-someone-intro',
    oops: 'you-have-gone-wrong',
    thanks: 'thanks',

    // gov
    overview: 'overview',
    whatYoullGet: 'what-youll-get',
    eligibility: 'eligibility',
    howToClaim: 'how-to-claim',
    reportChangeInCircumstances: 'report-change-in-circumstances',

    // scaling
    limitReached: 'limit-reached',
    ageRangeCheck: 'age-range-check',
    ageRangeIneligible: 'age-range-ineligible',
    ageRangeLimit: 'age-range-limit',
    ageRangeUnderStatePension: 'age-range-under-state-pension',
    ageRange: 'age-range',

    // visiting service
    effectiveDate: 'effective-date',

    // claim type
    claimType: 'claim-type',
    claimTypeChangeInCircumstances: 'claim-type-change-in-circumstances',
    claimTypeRenewal: 'claim-type-renewal',

    // eligibility
    whoIsApplying: 'who-is-applying',
    bestDescribe: 'best-describe',
    whoIsApplyingIneligible: 'who-is-applying-ineligible',
    personClaimingIneligible: 'person-claiming-ineligible',
    birthDate: 'birth-date',
    birthDateIneligible: 'birth-date-ineligible',
    otherBenefits: 'other-benefits',
    otherBenefitsIneligible: 'other-benefits-ineligible',
    pipIneligible: 'pip-ineligible',
    dlaIneligible: 'dla-ineligible',
    adpIneligible: 'adp-ineligible',
    nationality: 'nationality',
    nationalityOther: 'nationality-other',
    livingInUk: 'living-in-uk',
    residenceCountry: 'residence-country',
    previousResidenceScotland: 'previous-residence-scotland',
    previousClaimPadp: 'previous-claim-padp',
    residenceCountryNorthernIreland: 'residence-country-northern-ireland',
    residenceCountryIneligible: 'residence-country-ineligible',
    countryOutsideUKDuration: 'country-outside-uk-duration',
    countryOutsideUKDurationInelgible: 'country-outside-uk-duration-ineligible',
    countryOutsideUKBenefits: 'country-outside-uk-benefits',
    countryOutsideUKWorking: 'country-outside-uk-working',
    attendanceAllowanceIneligible: 'attendance-allowance-ineligible',

    // official capacity
    representativeIntro: 'representative-intro',
    representativeContactInformation: 'representative-contact-information',
    representativeName: 'representative-name',
    representativeNationalInsurance: 'representative-national-insurance',
    representativeBirthDate: 'representative-birth-date',
    representativeAddress: 'representative-address',
    representativeAddressPostcode: 'representative-address-postcode',
    representativeAddressSelect: 'representative-address-select',
    representativeAddressManual: 'representative-address-manual',
    representativeAddressInternational: 'representative-address-international',
    representativeTelephoneNumber: 'representative-telephone-number',

    // identity
    nationalInsurance: 'national-insurance',
    fullName: 'full-name',
    homeAddressPostcode: 'home-address-postcode',
    homeAddressSelect: 'home-address-select',
    homeAddressManual: 'home-address-manual',
    homeAddressInternational: 'home-address-international',

    // payability
    careHomeHospital: 'care-home-hospital',
    hospitalAddress: 'hospital-address',
    careHomeAddress: 'care-home-address',
    hospiceAddress: 'hospice-address',
    similarPlaceAddress: 'similar-place-address',
    careHomeFunding: 'care-home-funding',
    careHomeFundingWho: 'care-home-funding-who',
    careHomeFundingTrusts: 'care-home-funding-trusts',
    careHomeHospitalAdmissionDate: 'care-home-hospital-admission-date',
    hospitalAdmissionDate: 'hospital-admission-date',
    careHomeAdmissionDate: 'care-home-admission-date',
    hospiceAdmissionDate: 'hospice-admission-date',
    hospitalFunding: 'hospital-funding',
    careHomeHospitalOvernight: 'care-home-hospital-overnight',
    careHomeHospitalOvernightInformation: 'care-home-hospital-overnight-information',
    accommodationAddressOutsideUk: 'accommodation-address-outside-uk',
    sercoCareHomeHospital: 'serco-care-home-hospital',

    // special rules
    specialRulesDeclaration: 'special-rules-declaration',
    specialRulesFormCompleted: 'special-rules-form-completed',
    specialRulesFormSent: 'special-rules-form-sent',
    specialRulesFormUploadOption: 'special-rules-form-upload-option',
    specialRulesFormType: 'special-rules-form-type',
    specialRulesFormGuidance: 'special-rules-form-guidance',
    specialRulesFormUpload: 'special-rules-form-upload',
    specialRulesFormUploadRows: 'special-rules-form-upload-rows',
    specialRulesFormRemove: 'special-rules-form-remove',
    specialRulesFormAdded: 'special-rules-form-added',

    // health conditions
    healthConditions: 'health-conditions',
    healthConditionsAdded: 'health-conditions-added',
    healthConditionsManual: 'health-conditions-manual',
    healthConditionsRemove: 'health-conditions-remove',
    healthConditionsRows: 'health-conditions-rows',

    // illness and disabilities
    illnessDisability: 'illness-disability',
    illnessDisabilityAdded: 'illness-disability-added',
    illnessDisabilityRemove: 'illness-disability-remove',
    illnessDisabilityManual: 'illness-disability-manual',
    illnessDisabilityDate: 'illness-disability-date',
    illnessDisabilityDateManual: 'illness-disability-date-manual',

    // renal dyalisis
    renalDialysis: 'renal-dialysis',
    renalDialysisWhere: 'renal-dialysis-where',
    renalDialysisWhen: 'renal-dialysis-when',
    renalDialysisFrequency: 'renal-dialysis-frequency',
    renalDialysisHelp: 'renal-dialysis-help',

    // surgery or treatment
    treatmentSurgery: 'treatment-surgery',
    treatmentSurgeryInformation: 'treatment-surgery-information',

    // supporting documents
    supportingDocumentsIntro: 'supporting-documents-intro',
    supportingDocumentsOptions: 'supporting-documents-options',
    supportingDocumentsGuidance: 'supporting-documents-guidance',
    supportingDocumentsUpload: 'supporting-documents-upload',
    supportingDocumentsUploadRows: 'supporting-documents-upload-rows',
    supportingDocumentsRemove: 'supporting-documents-remove',
    supportingDocumentsAdded: 'supporting-documents-added',
    supportingDocumentsEmailLink: 'supporting-documents-email-link',
    supportingDocumentsEmailAddress: 'supporting-documents-email-address',
    supportingDocumentsUploadLater: 'supporting-documents-upload-later',
    supportingDocumentsPost: 'supporting-documents-post',

    // consent
    consent: 'consent',
    gpDetails: 'gp-details',
    healthcareProfessionalAdd: 'healthcare-professional-add',
    healthcareProfessionalOptions: 'healthcare-professional-options',
    healthcareProfessionalDetails: 'healthcare-professional-details',
    surgeryMedicalCentre: 'surgery-medical-centre',
    surgeryMedicalCentreOutsideUk: 'surgery-medical-centre-outside-uk',
    evidence: 'evidence',

    // care needs daytime
    dayDifficulties: 'day-difficulties',
    difficultiesStartDate: 'difficulties-start-date',
    bedDay: 'bed-day',
    bedDayWhy: 'bed-day-why',
    returnBedDay: 'return-bed-day',
    washDay: 'wash-day',
    washDayWhy: 'wash-day-why',
    additinalWashDay: 'additional-wash-day',
    dressDay: 'dress-day',
    dressDayWhy: 'dress-day-why',
    additionalDressDay: 'additional-dress-day',
    movingIndoorsDay: 'moving-indoors-day',
    movingIndoorsWhy: 'moving-indoors-why',
    movingIndoorsStairs: 'moving-indoors-stairs',
    fallingOrStumbling: 'falling-or-stumbling',
    fallingOrStumblingWhy: 'falling-or-stumbling-why',
    stumbling: 'stumbling',
    fallingWhen: 'falling-when',
    falling: 'falling',
    fallingHelp: 'falling-help',
    toiletDay: 'toilet-day',
    toiletDayWhy: 'toilet-day-why',
    toiletDayFrequency: 'toilet-day-frequency',
    eatDrinkDay: 'eat-drink-day',
    eatDrinkDayWhy: 'eat-drink-day-why',
    eatDrinkDayFrequency: 'eat-drink-day-frequency',
    medicationTreatmentDay: 'medication-treatment-day',
    medicationTreatmentDayWhy: 'medication-treatment-day-why',
    medicationTreatmentDayFrequency: 'medication-treatment-day-frequency',
    socialActivitiesDay: 'social-activities-day',
    socialActivitiesDayFrequency: 'social-activities-day-frequency',
    communicationDay: 'communication-day',
    communicationDayFrequency: 'communication-day-frequency',
    communicationDayDifficulties: 'communication-day-difficulties',
    keepEyeIntroduction: 'keep-eye-introduction',
    keepEyeChoice: 'keep-eye-choice',
    keepEyeWhy: 'keep-eye-why',
    keepEyeDuration: 'keep-eye-duration',
    safeDayNight: 'safe-day-night',
    safeDayWhy: 'safe-day-why',
    safeDayLength: 'safe-day-length',
    careNeedsCause: 'care-needs-cause',

    // night time care needs
    turningOverNightFrequency: 'turning-over-night-frequency',
    nightDifficulties: 'night-difficulties',
    bedPositionNight: 'bed-position-night',
    bedPositionNightFrequency: 'bed-position-night-frequency',
    toiletNight: 'toilet-night',
    toiletNightWhy: 'toilet-night-why',
    toiletNightFrequency: 'toilet-night-frequency',
    cleaningSoiledNight: 'cleaning-soiled-night',
    cleaningSoiledNightFrequency: 'cleaning-soiled-night-frequency',
    medicationTreatmentNight: 'medication-treatment-night',
    medicationTreatmentNightWhy: 'medication-treatment-night-why',
    medicationTreatmentNightFrequency: 'medication-treatment-night-frequency',
    watchOverYouIntro: 'watch-over-you-intro',
    watchOverNight: 'watch-over-night',
    watchOverNightWhy: 'watch-over-night-why',
    watchOverNightFrequency: 'watch-over-night-frequency',
    safeNightFrequency: 'safe-night-frequency',
    safeNightLength: 'safe-night-length',

    // aids adptations
    aidsAdaptationsQuestion: 'aids-adaptations-question',
    aidsAdaptationsReason: 'aids-adaptations-reason',
    aidsAdaptations: 'aids-adaptations',
    aidsAdaptationsDifficulty: 'aids-adaptations-difficulty',
    aidsAdaptationsAdded: 'aids-adaptations-added',
    aidsAdaptationsRemove: 'aids-adaptations-remove',

    // contact details
    telephoneNumber: 'telephone-number',
    addContactDetails: 'add-contact-details',
    telephoneNumberOther: 'telephone-number-other',
    preferenceContact: 'preference-contact',
    welshLanguageSpeak: 'welsh-language-speak',
    welshLanguageWrite: 'welsh-language-write',
    alternativeFormats: 'alternative-formats',
    emailSubmit: 'email-submit',
    emailConfirm: 'email-confirm',

    // check your answers
    checkAnswersDetails: 'check-answers-details',
    checkAnswersDay: 'check-answers-day',
    checkAnswersNight: 'check-answers-night',
    checkAnswersStartDate: 'check-answers-start-date',
    checkAnswersContactDetails: 'check-answers-contact-details',
    checkAnswersSpecialRules: 'check-answers-special-rules',

    // claim submission
    claimSubmission: 'claim-submission',
    sercoLateApplication: 'serco-late-application',
    checkAnswersFullList: 'check-answers-full-list',
    done: 'done',

    // accessiblity
    accessibilityStatement: 'accessibility-statement',

  },
  validation: {
    checkboxes: 'checkboxes',
    dateInput: 'dateInput',
    radios: 'radios',
    select: 'select',
    textInput: 'textInput',
    match: 'match',
    upload: 'upload',
  },
  match: {
    value: 'value',
    anyOne: 'any-one',
    anyInObject: 'any-in-object',
    all: 'all',
    none: 'none',
    greaterThan: 'greater-than',
    lessThan: 'less-than',
    session: 'session',
    sessionAndValue: 'sessionAndValue',
  },
  options: {
    none: 'none',
  },
};
